twig:
    file_name_pattern: '*.twig'
    globals:
        business:
            name: '%business.name%'
            ico: '%business.ico%'
            city: '%business.city%'
            email: '%business.email%'
            phone: '%business.phone%'
            phone_display: '%business.phone_display%'
            linkedin: '%business.linkedin%'
        ga_measurement_id: '%env(GA_MEASUREMENT_ID)%'

when@test:
    twig:
        strict_variables: true
